### ISSUE TITLE
distingushing VT types

### ISSUE THREAD

**Issue by marcurdy** [keithjjones/hostintel#6]
Can you add support for ssdeep and imphashes?  VT specifically i've tried.

**Comment by keithjjones** [comment]
Thanks for bringing this up.

Is this for hosts?  Or for files?  I don't recall hosts having any type of hash.  hostintel should fail on any type of hash.  I think you might want to file this under the fileintel tool I wrote?  Fileintel only supports MD5 and SHA hashes at the moment.  I don't know the answer if I can add support or not to fileintel.  Can you provide some samples or something for me to work towards?  If so, you can file an issue on fileintel with what the functionality should look like.  I will also happily look at pull requests.  Since this is not functionality I personally need soon and I'm kind of swamped, this is something that might not get done quickly.

**Comment by keithjjones** [comment]
https://github.com/keithjjones/fileintel/ is the other tool.

**Comment by marcurdy** [comment]
Yes, fileintel.  Outside of just mda5 and sha, I don't see much love out
there in general, but it's a vast world.

I work with a friend of yours I believe. Josh Dalman.

Cheers.

**Comment by keithjjones** [comment]
Ok, if you want a feature added to fileintel, please put it on that project's issues.  I'm going to close this issue since it doesn't apply to hostintel.  Check out my suggestion above about how to help get this into fileintel if you would like to see that functionality.

Yes, Josh and I go way back!
